# Generated by Django 2.2.5 on 2019-11-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0003_auto_20191124_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_loge',
            new_name='album_logo',
        ),
    ]
