# Generated by Django 2.2.5 on 2019-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0004_auto_20191124_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.CharField(max_length=750),
        ),
    ]
