# Generated by Django 2.2.5 on 2019-11-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_poc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdatabase',
            old_name='text_box',
            new_name='Data',
        ),
    ]
