# Generated by Django 2.2.5 on 2019-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_poc', '0002_auto_20191126_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdatabase',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
